//
//  AboutView.swift
//  App identity, privacy summary, and version.
//

import SwiftUI

struct AboutView: View {
    private var version: String {
        let v = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0"
        let b = Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "1"
        return "\(v) (\(b))"
    }

    var body: some View {
        List {
            Section {
                VStack(spacing: 10) {
                    Image("AppLogo")
                        .resizable()
                        .frame(width: 96, height: 96)
                        .clipShape(RoundedRectangle(cornerRadius: 21, style: .continuous))
                        .shadow(color: .black.opacity(0.18), radius: 8, y: 4)
                    Text("CalorieCounter").font(.title2.weight(.semibold))
                    Text("Version \(version)").font(.footnote).foregroundStyle(.secondary)
                }
                .frame(maxWidth: .infinity)
                .padding(.vertical, 8)
                .listRowBackground(Color.clear)
            }

            Section {
                Label("Your food log, weights, targets, and settings are stored only on this device.", systemImage: "lock.shield")
                Label("Typed, spoken, and photographed foods are analyzed in the cloud — the text (or photo) is sent for a nutrition estimate, nothing else.", systemImage: "sparkles")
                Label("Voice is transcribed on-device; only the recognized words are sent.", systemImage: "mic")
                Label("Scanning a barcode looks it up in Open Food Facts; if that product has no nutrition there, its name is sent for a cloud estimate.", systemImage: "barcode.viewfinder")
            } header: {
                Text("Privacy")
            } footer: {
                Text("Food descriptions and photos are sent to our service for analysis; your log, weights, and targets never leave the device. No tracking, no analytics.")
            }
            .font(.subheadline)

            Section {
                Label("Apple Health is optional and off until you turn it on.", systemImage: "heart.text.square")
            } footer: {
                Text("When enabled, the app can save nutrition and weigh-ins to Apple Health, import weight you already have there, and read completed workouts to offer a calorie offset. Workouts are read only — never written. Your food log, targets, weights, and settings stay on this device and are never synced to a server.")
            }
            .font(.subheadline)

            Section {
                Label("Targets are estimates, not medical advice.", systemImage: "stethoscope")
            } footer: {
                Text("Calorie and macro targets use the Mifflin–St Jeor formula and standard activity factors — a sensible starting point, not personalized nutrition therapy. If you have a health condition or specific goals, check with a doctor or registered dietitian.")
            }
            .font(.subheadline)

            Section {
                Label("Barcode and branded-product data from Open Food Facts (Open Database License).",
                      systemImage: "barcode")
                    .font(.subheadline)
                Link(destination: URL(string: "https://world.openfoodfacts.org/")!) {
                    Label("openfoodfacts.org", systemImage: "arrow.up.right")
                        .font(.subheadline)
                }
            } header: {
                Text("Data Sources")
            } footer: {
                Text("Barcode and branded-product nutrition comes from the Open Food Facts database, made available under the Open Database License (ODbL). Calorie and macro estimates for typed, spoken, and photographed food are generated by AI and are approximate — always check and adjust them before saving.")
            }

            Section {
                LabeledContent("Built by", value: "Marco van Hylckama Vlieg")
            } footer: {
                Text("© 2026 Unthinking AI, LLC. All rights reserved.")
            }
        }
        .navigationTitle("About")
        .navigationBarTitleDisplayMode(.inline)
    }
}
